services:
  colyseus:
    build: .
    depends_on:
      - db
    ports:
      - "2567:2567"
    volumes:
      - .:/app   
    command: node build/index.js
  db:
    image: bitnami/postgresql
    ports: 
      - '5432:5432'
    env_file:
      - .env.docker
    volumes:
      - db_data:/bitnami/postgresql

volumes:
  db_data:
    
