services:
  colyseus:
    build: .
    depends_on:
      - db
    ports:
      - "2567:2567"
    environment:
      - DATABASE_URL=postgres://test:123456@db:5432/colyseus
    volumes:
      - .:/app   
    command: npm start
  db:
    image: bitnami/postgresql
    ports: 
      - '5432:5432'
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=colyseus
      - DATABASE_URL=postgres://test:123456@db:5432/colyseus
    volumes:
      - db_data:/bitnami/postgresql

volumes:
  db_data:
    